### ISSUE TITLE
problem with non-JIT pcre2

### ISSUE THREAD

**Issue by 0-wiz-0** [gvansickle/ucg#100]
`ucg` compiled with pcre seems to work fine.
When compiled with pcre2-10.22, it builds fine but fails for me at runtime with:
````
path/to/ucg -r pcre path/to/ucg-source
/ucg: error: Error during regex parsing: PCRE2 JIT compilation error: bad JIT option
```
Not sure what this is about (and there's a weird '/' at the start of the line).
`ucg --version` output:
````
Compiler info:
 Name ($(CXX)): c++ -std=gnu++11
 Version string: "g++ (nb1 20160606) 5.4.0"

ISA extensions in use:
 sse4.2: yes
 popcnt: yes

libpcre info:
 Not linked against libpcre.

libpcre2-8 info:
 Version: 10.22 2016-07-29
 JIT support built in?: no
 JIT target architecture: none
 Newline style: LF
````
pcre2's self tests run fine.

**Comment by gvansickle** [comment]
Hi @0-wiz-0 ,
Does this happen with any regex/literal, or just with 'pcre'.  I.e., does it work at all for you with PCRE2?

**Comment by 0-wiz-0** [comment]
This also happens with real regex, like:
````
ucg -r univ.*code.*rep path/to/ucg
/ucg: error: Error during regex parsing: PCRE2 JIT compilation error: bad JIT option
````

**Comment by gvansickle** [comment]
Oh, wait:
```
libpcre2-8 info:
 Version: 10.22 2016-07-29
 JIT support built in?: no
 JIT target architecture: none
```
No JIT is almost certainly the problem.  Does NetBSD have a JIT-enabled PCRE2 available via its package manager or some other reasonable means?

The question of whether to support a no-JIT PCRE/PCRE2 or not has been nagging at me for some time.  It's part of the secret sauce that makes `ucg` "Faster Than Grep"(tm) in its target use cases.  Conversely, having a completely non-working `ucg` benefits nobody....

**Comment by 0-wiz-0** [comment]
I've just built pcre2 with JIT support, and ucg now works fine both with strings and actual regexp.
Perhaps you can improve the error handling in this case :-)

One other issue: on a PaX MPROTECT system, ucg built this way needs to be marked as not MPROTECT safe. On NetBSD this is done by calling 'paxctl +m ucg' after the build is finished. (see http://netbsd.gw.com/cgi-bin/man-cgi?paxctl++NetBSD-current)
On Linux, it's done using 'paxctl -m ucg' (see https://wiki.gentoo.org/wiki/Hardened/PaX_Quickstart#paxctl).
This is a property of the file, so it can be done before installation or after (but take that the real binary, and not a libtool shell wrapper script, is the target).

**Comment by gvansickle** [comment]
Hi again @0-wiz-0 ,

> I've just built pcre2 with JIT support, and ucg now works fine both with strings and actual regexp.
> Perhaps you can improve the error handling in this case :-)

Indeed.  I think I've decided that I should require a JIT-enabled PCRE/PCRE2 at configure-time, which would eliminate this as an error.

> One other issue: on a PaX MPROTECT system, ucg built this way needs to be marked as not MPROTECT safe. 

Yeah, I've been wondering when I was going to run into issues with JIT vs. the NX bit.  Thanks for the info; I'll file a separate issue for that.
