### ISSUE TITLE
Add at least a minimal man page

### ISSUE THREAD

**Issue by gvansickle** [gvansickle/ucg#44]
rpmlint complains, and we really should have something.

**Comment by gvansickle** [comment]
@larryhynes was good enough to write up a man page on pull request Man page for ucg #105.  Now we need to integrate it into the build system.

**Comment by gvansickle** [comment]
Hey @larryhynes , now that is high-class!  Doesn't look like too much to touch up, but I did rearrange the --help somewhat, so I'll make that match up.  Thanks again.

**Comment by larryhynes** [comment]
Great stuff, happy to help.
