### ISSUE TITLE
Key '--color' don't output right for less command

### ISSUE THREAD

**Issue by proggga** [gvansickle/ucg#52]
if you will use
```# ucg --color mypattern | less```
it will be without colored text, and ```less -r``` doesn't work too,
but for example:
```git diff --color=always| less -r```

Please check it out

**Comment by proggga** [comment]
Yes, I've checked this,
It doesn't write color symbols to file, or any kind of pipe
Checked on 'openSUSE 13.2 (Harlequin) (x86_64)'

**Comment by gvansickle** [comment]
You're right, I see that ack and ag output color symbols to non-ttys when given the --color option.
