### ISSUE TITLE
Pattern used as File/Directory

### ISSUE THREAD

**Issue by Patterner** [gvansickle/ucg#53]
> ucg --help
Usage: ucg [OPTION...] PATTERN [FILES OR DIRECTORIES]

> ucg pattern
ucg: "pattern": No such file or directory

**Comment by gvansickle** [comment]
Hi @Patterner,
I can't reproduce this.  Can you give me more details?  E.g. platform, ucg --version, if you have any .ucgrc files and their contents?

**Comment by Patterner** [comment]
typo in .ucgrc, sorry.
