### ISSUE TITLE
Add --include=/--exclude= or equivalent file filters

### ISSUE THREAD

**Issue by kirbyfan64** [gvansickle/ucg#84]
`ag` has `--ignore=...`. `ucg` seems to require `--type-add='whatever:is:...' --nowhatever`. This can be somewhat annoying at times...

Maybe add a `--filter`/`--nofilter` argument set? It would take arguments like `--type` does, so one could use it like `--filter=ext:c` or whatever.

**Comment by gvansickle** [comment]
`ack` has `--ignore-file=filter` for this same purpose.  `grep` has `--exclude=FILE_PATTERN`.

**Comment by gvansickle** [comment]
@kirbyfan64 , how are you using ucg?  Are you using pre-built binaries, or building from a tarball, or building from a git clone?

**Comment by kirbyfan64** [comment]
@gvansickle Git, though I admittedly haven't updated in a month. Probably should around now...

**Comment by gvansickle** [comment]
@kirbyfan64 Ok great.  I just pushed multithreaded dir tree traversal, so that's worth picking up, and I'm working on this issue now, and with any luck will have it done this weekend.  Building binary distros is a major pain, so it's good to know you'll be able to pick this up as soon as I merge it to master.

**Comment by gvansickle** [comment]
Ok @kirbyfan64 , FYI: I'm getting there.  As of e8f71bb3e71467241ed5043091bbd6896d378848 (feature/ISSUE84-IncludeExclude), I have `ack`-style `--ignore-file=FILTER:FILTERARGS` working, and `grep`-style `--exclude=GLOB` working "good enough".  I may not get all the above options feature-complete (I think ag `--ignore=GLOB` might just be files, not dirs) or 100% how I'd like (integrating glob pattern "on/off" with the other filters in the way I really want to is proving to be problematic) on this branch, but they'll be useful.  Hopefully this weekend.

**Comment by kirbyfan64** [comment]
@gvansickle Thanks!

**Comment by gvansickle** [comment]
There you go @kirbyfan64 !  See trunk, let me know what you think.

**Comment by kirbyfan64** [comment]
@gvansickle Thanks! It works really well! Out of curiosity, is there eventually going to be a way to exclude directories?

**Comment by gvansickle** [comment]
Hi @kirbyfan64 ,
From the `--help`:
`--[no]ignore-dir=name, --[no]ignore-directory=name
                             [Do not] exclude directories with this name.`
Now, the dir name has to match exactly, at least currently; if you're asking about globbing etc of dir names, that's a definite maybe.  Please file an enhancement request to that effect if you think it would be a useful feature.
Take care, GRVS.
