### ISSUE TITLE
dirname() compatibility

### ISSUE THREAD

**Issue by 0-wiz-0** [gvansickle/ucg#96]
There are two kinds of implementations of dirname(3), both valid according to POSIX. One modifies its argument, one doesn't but returns a static buffer instead (see http://pubs.opengroup.org/onlinepubs/009695399/functions/dirname.html)
NetBSD provides a version of the second one.
ucg reliable dumps core when it tries to find its home directory, because it calls dirname() on the result of dirname().

Here's a possible patch which stops the core dumps:
````
--- src/ArgParse.cpp.orig       2016-04-11 00:11:55.000000000 +0000
+++ src/ArgParse.cpp
@@ -663,6 +663,7 @@ std::string ArgParse::GetProjectRCFilena
        char *current_cwd = original_cwd;
        while((current_cwd != nullptr) && (current_cwd[0] != '.'))
        {
+               char *prev_cwd;
                // If we were able to get a file descriptor to $HOME above...
                if(home_fd != -1)
                {
@@ -710,7 +711,9 @@ std::string ArgParse::GetProjectRCFilena
                }
 
                // Go up one directory.
-               current_cwd = dirname(current_cwd);
+               prev_cwd = strdup(current_cwd);
+               current_cwd = dirname(prev_cwd);
+               free(prev_cwd);
        }
 
        // Free the cwd string.
````

**Comment by gvansickle** [comment]
Hmmm:

> The dirname() function may modify the string pointed to by path, and may return a pointer to static storage that may then be overwritten by subsequent calls to dirname().

And here's me like a chump thinking I was being portable just _using_ dirname(). ;-)  Seriously, these APIs that may or may not, but definitely could possibly alter their parameters and/or be using a static buffer but by gum don't look at the buffer for too long or it will segfault all over your shirt belong to that dustbin of history I keep hearing about.

Thanks for the patch; I want to think on this a bit after I've had more sleep....

**Comment by gvansickle** [comment]
Hi @0-wiz-0 ,
I just checked in a fix for this on master at 4f782cd.  I went a more C++ish route for the fix, basically wrapping dirname() in a C++ function taking std::strings and encapsulating the strdup()/free() there.

Can you give this version a try and let me know if it fixes the issue?  It passes all my regressions on Linux, OSX, and PC/FreeBSD, but for unknown reasons it always did before too, so I'd really appreciate it.

Thanks again for the report and the patch!

GRVS

**Comment by 0-wiz-0** [comment]
Thanks for the quick fix! I couldn't test it yet though.

First issue: configure.ac uses "==" as test operator in two places, that's not portable, only bash(1) supports it. Use a single "=" instead.

Second issue: the script(1) detection breaks for me, `config.log` has:
````
configure:15970: checking for script
configure:15988: found /usr/bin/script
configure:16001: result: /usr/bin/script
configure:16009: checking /usr/bin/script's command line type
configure:16033: error: could not determine how to invoke /usr/bin/script
````
I tried running the tests manually, but both versions work for me on NetBSD-7.99.38/amd64:
````
# script -qfc "echo hello" /dev/null
hello
# echo $?
0
# script -q /dev/null echo hello
# echo $?
0
````
The second version enters a subshell though. If I run the second version without `-q`:
````
# script /dev/null  echo hello
Script started, output file is /dev/null
#<CTRL-D>
Script done, output file is /dev/null
````

**Comment by gvansickle** [comment]
If you comment out the `script` check in configure.ac (lines 130-145), can you get through the rest of the build?  Some of the `make check` tests will fail, but you should still get a usable `ucg`.

**Comment by gvansickle** [comment]
PS: I just changed the two '==' to '=' in configure.ac and committed the change master/HEAD.

**Comment by 0-wiz-0** [comment]
Thanks for the `configure.ac` fix.
I've just tested compilation with the `script(1)` detection disabled, and the original problem in this issue is indeed fixed. Thank you!
Except for the `script` test, I found another problem though when compiling with pcre2 (instead of pcre):
````
path/to/ucg -r pcre path/to/ucg-source
/ucg: error: Error during regex parsing: PCRE2 JIT compilation error: bad JIT option
````
Not sure what this is about (and there's a weird '/' at the start of the line).
The same command works with pcre.
Let me know if I should open new issues for any of these.
Thanks!

**Comment by gvansickle** [comment]
Hi @0-wiz-0 ,
Thanks for the testing, and thanks again for the original report; like I said, this dirname() issue was never triggering for me on any of the different platforms I've been testing on, even though at least some of them certainly should have segfaulted.  Nor did I ever catch it with valgrind/memcheck.  Who knows how long this would have laid dormant.

Yes, if you would, please open new issues for both the `script` issue and the `PCRE2` issue, and then we can close this one as fixed.  In particular with the PCRE2 issue, please record as much detail as you can; I can't reproduce either the `bad JIT option` or the `/` in '/ucg` here, so I'm flying blind.  Let me know if you get this issue with any regex or just particular ones (though having an issue with a literal 'pcre' sounds pretty broken), if the search path and/or exe path seem to matter, etc.  And especially if you can include the output of `./ucg --version` (which will report what version of PCRE2 you have), that should help a lot.  My SWAG here is that it's an older version of PCRE2 that doesn't support one of the options I'm passing it.

Thanks again,
GRVS

**Comment by 0-wiz-0** [comment]
Ah, I never answered your question about that: I think I saw the core dump because I'm compiling with stack protector turned on by default.
I'll open more bug reports now :-)
